"""Data loader for Milvus (PoC)
Requirements:
pip install openai pymilvus

This script is an example to:
1. Create collection 'faq_orders'
2. Insert sample FAQ text with embeddings generated by OpenAI

Set environment variable OPENAI_API_KEY before running.
"""
from pymilvus import connections, FieldSchema, CollectionSchema, DataType, Collection
import openai, os

OPENAI_KEY = os.getenv('OPENAI_API_KEY', '')
if not OPENAI_KEY:
    print('Please set OPENAI_API_KEY in environment to generate real embeddings. Using mock vectors.')

connections.connect("default", host="localhost", port="19530")

fields = [
    FieldSchema(name="id", dtype=DataType.INT64, is_primary=True, auto_id=True),
    FieldSchema(name="question", dtype=DataType.VARCHAR, max_length=1024),
    FieldSchema(name="answer", dtype=DataType.VARCHAR, max_length=2048),
    FieldSchema(name="embedding", dtype=DataType.FLOAT_VECTOR, dim=1536)
]
schema = CollectionSchema(fields, description="FAQ for orders")
if Collection.exists("faq_orders"):
    coll = Collection("faq_orders")
else:
    coll = Collection("faq_orders", schema=schema)

samples = [
    ["下单成功但未回调"],
    ["订单卡在处理中"],
]
answers = [
    ["检查回调日志与MQ消费状态。"],
    ["检查渠道回执、对账任务和订单中心同步。"],
]

vectors = []
if OPENAI_KEY:
    openai.api_key = OPENAI_KEY
    for q in samples:
        resp = openai.Embedding.create(model="text-embedding-3-large", input=q[0])
        vectors.append(resp['data'][0]['embedding'])
else:
    import random
    for _ in samples:
        vectors.append([random.random() for _ in range(1536)])

insert_data = [samples, answers, vectors]
coll.insert(insert_data)
coll.flush()
print('Inserted sample FAQs into Milvus (faq_orders)')